[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
zbus = "5"
rand = { version = "0.9.2" }
futures-util = "0.3"
urlencoding = "2.1.3"
tesseract = "0.15"
eframe = "0.28.1"
